# Generated by Django 5.2.9 on 2026-03-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='base_cliente',
        ),
        migrations.AlterModelTable(
            name='transaccion',
            table='base_transaccion',
        ),
    ]
