# Generated by Django 5.2.9 on 2026-03-09 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_transaccion_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('DEUDA', 'Deuda Normal'), ('REPORTADO', 'Deuda Reportada')], default='DEUDA', max_length=20)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total_a_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_meses', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='deuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.deuda'),
        ),
    ]
