# Generated by Django 5.2.9 on 2026-03-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_deuda_transaccion_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
