# Generated by Django 5.2.8 on 2025-12-07 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('documento_identidad', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre'), ('NIÑO', 'Niño')], max_length=10)),
                ('categoria', models.CharField(choices=[('JJ', 'Joyería'), ('PP', 'Perfumería'), ('AA', 'Accesorios')], max_length=2)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_entrega', models.IntegerField(help_text='Días estimados de entrega')),
                ('fecha_disponibilidad', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiempo_entrega', to='ingresos.producto')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Entrega',
                'verbose_name_plural': 'Disponibilidades de Entrega',
                'db_table': 'disponibilidad_entrega',
            },
        ),
    ]
