"""
Django settings for Movimientos project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-&pe^@zjnf8u04rhzr*86)3=n9&1#q5rc21mdi=31*@wvi%wxyk')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*', '*.railway.app']
RAILWAY_STATIC_URL = os.environ.get('RAILWAY_STATIC_URL', '')
if RAILWAY_STATIC_URL:
    ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aplicaciones.base',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para archivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Movimientos.urls'

# ─────────────────────────────────────────────────────────────
# PEGA ESTO en Movimientos/settings.py
# Reemplaza el bloque TEMPLATES que ya tienes
# ─────────────────────────────────────────────────────────────

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ↓ ESTA ES LA LÍNEA CLAVE que faltaba
        # Le dice a Django dónde buscar templates fuera de las apps
        'DIRS': [BASE_DIR / 'aplicaciones' / 'base' / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Movimientos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de base de datos para Railway (PostgreSQL) o desarrollo (SQL Server)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Configuración de desarrollo con SQL Server
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
             'NAME': 'DJANGO_MOVIMIENTOS',
            'USER': 'Jefrino',
            'PASSWORD': 'Emily2713*cas',
            'HOST': 'DESKTOP-7L879NC\\SQLEXPRESS',
            'PORT': '1433',
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-Co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

MEDIA_URL= '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Abre el archivo settings.py de tu carpeta de proyecto
ALLOWED_HOSTS = ['6b71-152-201-102-254.ngrok-free.app', 'localhost', '127.0.0.1', '*']
# Permite cualquier subdominio de ngrok (solo en desarrollo)
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
if RAILWAY_STATIC_URL:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_STATIC_URL}")

STATIC_URL = '/static/'

import os  # ← Asegúrate de tener esto al inicio del archivo

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Carpeta donde se recopilarán todos los archivos estáticos en producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Carpetas adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise para servir archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# ==========================================
# CONFIGURACIÓN DE AUTENTICACIÓN
# ==========================================

# Redirige al dashboard después de login exitoso
LOGIN_REDIRECT_URL = '/dashboard/'

# URL de la página de login
LOGIN_URL = '/accounts/login/'

# Redirige al index después de logout
LOGOUT_REDIRECT_URL = '/'

# ==========================================
# CONFIGURACIÓN DE EMAIL (Desarrollo)
# ==========================================
# En desarrollo, los emails se imprimen en la consola
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Para producción, usar SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tuemail@gmail.com'
# EMAIL_HOST_PASSWORD = 'tucontraseña'
DEFAULT_FROM_EMAIL = 'Sistema de Movimientos <no-reply@movimientos.com>'

# ==========================================
# CONFIGURACIÓN DE LOGGING PARA RAILWAY
# ==========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}