# Generated by Django 5.2.8 on 2025-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=58)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
